import React from "react";
import AppLayout from "@/components/layout/AppLayout";
import { mockReports } from "@/lib/mockData";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Plus, Clock, FileCheck } from "lucide-react";

export default function Reports() {
  return (
    <AppLayout>
      <div className="mb-8 flex justify-between items-center">
        <div>
           <h1 className="text-3xl font-bold tracking-tight mb-2">Reports</h1>
           <p className="text-muted-foreground">Generate and download branded competitive intelligence reports.</p>
        </div>
        <Button>
            <Plus className="w-4 h-4 mr-2" /> Generate New Report
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {mockReports.map((report) => (
            <Card key={report.id} className="flex flex-col group hover:border-primary/50 transition-all duration-300">
                <CardHeader>
                    <div className="flex justify-between items-start mb-4">
                        <div className="w-10 h-10 rounded bg-primary/10 text-primary flex items-center justify-center">
                            <FileText size={20} />
                        </div>
                        <Badge variant={report.status === "Ready" ? "default" : "secondary"}>
                            {report.status}
                        </Badge>
                    </div>
                    <CardTitle className="line-clamp-1 group-hover:text-primary transition-colors">{report.name}</CardTitle>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1">
                        <Clock size={12} /> {report.date}
                        <span>•</span>
                        <span>{report.size}</span>
                    </div>
                </CardHeader>
                <CardContent className="flex-1">
                    <p className="text-sm text-muted-foreground line-clamp-3">
                        Comprehensive competitive analysis report covering key themes, messaging gaps, and AI-driven recommendations. Generated by {report.author}.
                    </p>
                </CardContent>
                <CardFooter className="border-t border-border pt-4">
                    <Button variant="outline" className="w-full group-hover:bg-primary group-hover:text-primary-foreground group-hover:border-primary transition-all">
                        <Download className="w-4 h-4 mr-2" /> Download {report.type}
                    </Button>
                </CardFooter>
            </Card>
        ))}
      </div>
    </AppLayout>
  );
}
