export const COMPANY_SIZES = [
  { value: "sole_proprietor", label: "Sole Proprietor (1)" },
  { value: "very_small", label: "Very Small (2-10)" },
  { value: "small", label: "Small (11-50)" },
  { value: "lower_mid", label: "Lower Mid-Market (51-200)" },
  { value: "upper_mid", label: "Upper Mid-Market (201-500)" },
  { value: "mid_enterprise", label: "Mid Enterprise (501-1000)" },
  { value: "large_enterprise", label: "Large Enterprise (1000+)" },
];

export const JOB_ROLES = [
  "C-Suite / Executive",
  "Vice President",
  "Director",
  "Manager",
  "Individual Contributor",
  "Consultant",
  "Analyst",
  "Founder / Owner",
  "Other",
];

export const INDUSTRIES = [
  "Technology",
  "Financial Services",
  "Healthcare",
  "Manufacturing",
  "Retail / E-commerce",
  "Professional Services",
  "Education",
  "Government",
  "Non-Profit",
  "Media / Entertainment",
  "Real Estate",
  "Telecommunications",
  "Transportation / Logistics",
  "Energy / Utilities",
  "Hospitality / Travel",
  "Agriculture",
  "Construction",
  "Consumer Goods",
  "Other",
];

export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "--- A-Z ---",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "China",
  "Denmark",
  "Finland",
  "France",
  "Germany",
  "India",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Poland",
  "Portugal",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "United Arab Emirates",
  "Other",
];
